---
title: "analysis_Theron_08262021"
author: "Theron Palmer"
date: "8/26/2021"
output: html_document
---

# Loading in necessary libraries

```{r,echo=FALSE}

library(dplyr)
library(knitr)
library(ggplot2)
library(TCGAutils)
library(maftools)
library(ggpubr)
library(stringr)
library(readxl)

```

# Processing TCGA mutation data

```{r}

mut_dat <- read_excel("/media/theron/My_Passport/TCGA_junctions/ext_dat/13073_2017_424_MOESM3_ESM_coded.xlsx")
mut_dat_complete<-mut_dat[complete.cases(mut_dat),]

```


The TCGA MAF summary file

```{r}

maf_file <- "/media/theron/My_Passport/TCGA_junctions/maf_summary.txt"
mc3_maf = read.table(maf_file,header=T)
mc3_maf$Tumor_Sample_ID <- vapply(TCGAbarcode(mc3_maf$Tumor_Sample_Barcode,sample=T),
                                  function(val){substr(val,1,nchar(val)-1)},
                                  character(1))
rownames(mc3_maf) <- mc3_maf$Tumor_Sample_Barcode
mc3_maf$participant_ID <- TCGAbarcode(mc3_maf$Tumor_Sample_Barcode,participant=T)
mc3_maf_miss <- mc3_maf[,c("Missense_Mutation","participant_ID")]

```

# Accumulating mutation data per sample

```{r,eval=F,echo=F}

junc_rse_file <- "/media/theron/My_Passport/TCGA_junctions/TCGA_cancers/CHOL/juncrse.rds"
junc_rse <- readRDS(junc_rse_file)
junc_metadata <- as.data.frame(junc_rse@colData@listData)
junc_rse_cols <- colnames(junc_metadata)

tumor_data_file <- "/media/theron/My_Passport/TCGA_junctions/TCGA_cancers/filenames.txt"
tumor_data <- read.table(tumor_data_file)
cancers <- basename(tumor_data$V1)
nogos <- c("ESCA","MESO","PAAD","KIRC")
TMB<-data.frame(cancers)

optitype_calls <- read.table("/media/theron/My_Passport/TCGA_junctions/ext_dat/OptiTypeCallsHLA_20171207.tsv",header=T,sep=",")
which_are_correct<-vapply(optitype_calls$aliquot_id,function(ID){
  a<-strsplit(ID,"-")[[1]]
    if (nchar(a[1]) > 4){
      return(F)  
    } else {
      return(T)
    }
},logical(1))
optitype_calls_correct <- optitype_calls[which_are_correct,]
optitype_calls_correct$particpant_ID <- TCGAbarcode(optitype_calls_correct$aliquot_id,participant=T)

for (i in seq(nrow(tumor_data))){
  print(sprintf("%d out of %d",i,nrow(tumor_data)))
  tumor_dir <- tumor_data[i,]
  cancer <- basename(tumor_dir)
  print(cancer)
  if (cancer %in% nogos){next}
  # tumor_geno_file <- sprintf("%s/%s_genotypes.txt",tumor_dir,cancer)
  # tumor_geno <- read.table(tumor_geno_file,header=T,sep="\t")
  tumor_meta_file <- sprintf("%s/%s_metadata.txt",tumor_dir,cancer)
  tumor_meta <- read.table(tumor_meta_file,quote="",sep="\t")
  tumor_meta$participant_ID <- TCGAbarcode(tumor_meta[,4],participant=T)
  tumor_meta$nbases<-tumor_meta[,ncol(tumor_meta)-9]
    
  mc3_maf_temp<-lapply(seq(length(tumor_meta$participant_ID)),function(val){
      nbases<-tumor_meta$nbases[val]
      mc3_maf_small <- subset(mc3_maf_miss,participant_ID == tumor_meta$participant_ID[val])
      if (nrow(mc3_maf_small)==0){
        a<-data.frame(t(c(NA,NA,NA)))
        colnames(a)<-c("Missense_Mutation","participant_ID","nbases")
        return(a)
      }
      mc3_maf_small$nbases <- nbases
      return(mc3_maf_small)
    })
  mc3_maf_small <- mc3_maf_temp[[1]]
  for (i in seq(length(mc3_maf_temp))){
    mc3_maf_small<-rbind(mc3_maf_small,mc3_maf_temp[[i]])
  }
  mc3_maf_small$nbases_MB <- mc3_maf_small$nbases/(1e6)
  mc3_maf_small$TMB<-mc3_maf_small$Missense_Mutation/mc3_maf_small$nbases_MB
  mc3_maf_small <- mc3_maf_small[complete.cases(mc3_maf_small),]
  mc3_maf_small$type <- vapply(rownames(mc3_maf_small),function(barcode){
    type<-as.numeric(substr(strsplit(barcode,"-")[[1]][4],1,2))
    if (type <= 9){
      return("T")
    } else if (type > 9 & type <= 19){
      return ("N")
    } else {
      return ("C")
    }
  },character(1))
  mc3_maf_small <- mc3_maf_small %>% dplyr::filter(type == "T")
  TMB[TMB$cancers==cancer,"Missense_Mutation_mean"] <-   mean(mc3_maf_small$Missense_Mutation/mc3_maf_small$nbases_MB,na.rm=T)
  TMB[TMB$cancers==cancer,"Missense_Mutation_median"] <-   median(mc3_maf_small$Missense_Mutation/mc3_maf_small$nbases_MB,na.rm=T)
}

```

# Processing the splicing imm data

## Accumulating per cluster metrics 

```{r,eval=F,echo=F}

tumor_data_file <- "/media/theron/My_Passport/TCGA_junctions/TCGA_cancers/filenames.txt"
tumor_data <- read.table(tumor_data_file)
cancers <- basename(tumor_data$V1)
cluster_metrics_tum <- data.frame(cancers)
cluster_metrics_tum$tumor_clusters <- NA
nogos <- c("ESCA","MESO","PAAD","KIRC")
for (i in seq(1,nrow(tumor_data))){
  print(sprintf("%d out of %d",i,nrow(tumor_data)))
  tumor_dir <- tumor_data[i,]
  cancer <- basename(tumor_dir)
  if (cancer %in% nogos){next}
  tumor_splicemutr_file <- sprintf("%s/%s_splicemutr_dat.txt",tumor_dir,cancer)
  tumor_splicemutr <- read.table(tumor_splicemutr_file,header=T,sep="\t")
  tumor_normal_kmers_file <- sprintf("%s/%s_tumor_normal_kmers.txt",tumor_dir,cancer)
  tumor_normal_kmers <- read.table(tumor_normal_kmers_file,header=T,sep="\t")
  cluster_metrics <- data.frame(unique(tumor_splicemutr$cluster))
  colnames(cluster_metrics)<-"cluster"
  tumor_splicemutr$peptide_length <- nchar(tumor_splicemutr$peptide)-1
  tumor_splicemutr <- cbind(tumor_splicemutr,tumor_normal_kmers[,seq(2,ncol(tumor_normal_kmers))])
  tumor_splicemutr_refined <- tumor_splicemutr %>% dplyr::filter(!is.na(peptide)) %>% 
    dplyr::filter(!(verdict == "annotated" & modified == "changed")) %>%
    dplyr::filter(peptide_length >= 20)
  tumor_splicemutr_refined$deltapsi <- as.numeric(tumor_splicemutr_refined$deltapsi)
  
  cluster_metrics$tum_not_norm <- vapply(cluster_metrics$cluster,function(clu){
    tumor_dat <- tumor_splicemutr_refined %>% dplyr::filter(cluster == clu)
    tumor_kmers <- tumor_dat$tumor[which(tumor_dat$deltapsi >0)]
    tumor_kmers <- unlist(str_split(tumor_kmers,":"))
    normal_kmers <- tumor_dat$tumor[which(tumor_dat$deltapsi <0)]
    normal_kmers <- unlist(str_split(normal_kmers,":"))
    tumor_kmers<-unique(tumor_kmers[!(tumor_kmers %in% normal_kmers)])
    return(length(tumor_kmers))
  },numeric(1))
  
  cluster_metrics_tum[cluster_metrics_tum$cancers==cancer,"tumor_clusters"] <- nrow(cluster_metrics %>% dplyr::filter(tum_not_norm > 0))
}
write.table(cluster_metrics_tum,file="/media/theron/My_Passport/TCGA_junctions/cluster_metrics.txt",
            sep="\t",
            quote=F,
            col.names=T,
            row.names=F)

```

```{r}

cluster_metrics_tum <- read.table("/media/theron/My_Passport/TCGA_junctions/cluster_metrics.txt",header=T)

```

## Joining TMB and cancer clusters together, plotting

```{r}

splice_ant_TMB <- mut_dat_complete
tumor_clusters<-vapply(seq(nrow(splice_ant_TMB)),function(row_val){
  code<-splice_ant_TMB$Code[row_val]
  a<-which(cluster_metrics_tum$cancers==code)
  if(length(a)==0){
    return(-1)
  } else {
    return(cluster_metrics_tum[a,"tumor_clusters"])
  }
},numeric(1))
splice_ant_TMB$tumor_clusters<-tumor_clusters
splice_ant_TMB_filt <- splice_ant_TMB %>% dplyr::filter(tumor_clusters != -1)
splice_ant_TMB_filt <- splice_ant_TMB_filt[seq(14),]
splice_ant_TMB_filt[7,"Code"]<-"BRCA(inv_duct)"
ggplot(splice_ant_TMB_filt,aes(x=log2(tumor_clusters),y=`Median TMB`,label=Code))+
  geom_text()+
  stat_cor(method = "spearman")+
  xlab("log2(splicing antigenicity)")

```

